## Step 1, 2 & 3. Import the necessary libraries, the dataset and assign it to a variable called iris

In [0]:
import pandas as pd
import numpy as np

In [13]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = pd.read_csv(url)
iris.head()

   5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

## Step 4. Create columns for the dataset

In [0]:
# 1. sepal_length (in cm)
# 2. sepal_width (in cm)
# 3. petal_length (in cm)
# 4. petal_width (in cm)
# 5. class

In [0]:
iris.columns = ['sepal_length','sepal_width', 'petal_length', 'petal_width', 'class']

In [15]:
iris.head()

   sepal_length  sepal_width  petal_length  petal_width        class
0           4.9          3.0           1.4          0.2  Iris-setosa
1           4.7          3.2           1.3          0.2  Iris-setosa
2           4.6          3.1           1.5          0.2  Iris-setosa
3           5.0          3.6           1.4          0.2  Iris-setosa
4           5.4          3.9           1.7          0.4  Iris-setosa

## Step 5. Is there any missing value in the dataframe?

In [16]:
pd.isnull(iris).sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
class           0
dtype: int64

## Step 6. Lets set the values of the rows 10 to 29 of the column 'petal_length' to NaN

In [0]:
iris.loc[10:29, 'petal_length' ] = np.NaN

In [18]:
iris.head(32)

    sepal_length  sepal_width  petal_length  petal_width        class
0            4.9          3.0           1.4          0.2  Iris-setosa
1            4.7          3.2           1.3          0.2  Iris-setosa
2            4.6          3.1           1.5          0.2  Iris-setosa
3            5.0          3.6           1.4          0.2  Iris-setosa
4            5.4          3.9           1.7          0.4  Iris-setosa
5            4.6          3.4           1.4          0.3  Iris-setosa
6            5.0          3.4           1.5          0.2  Iris-setosa
7            4.4          2.9           1.4          0.2  Iris-setosa
8            4.9          3.1           1.5          0.1  Iris-setosa
9            5.4          3.7           1.5          0.2  Iris-setosa
10           4.8          3.4           NaN          0.2  Iris-setosa
11           4.8          3.0           NaN          0.1  Iris-setosa
12           4.3          3.0           NaN          0.1  Iris-setosa
13           5.8          4.0           NaN          0.2  Iris-setosa
14           5.7          4.4           NaN          0.4  Iris-setosa
15           5.4          3.9           NaN          0.4  Iris-setosa
16           5.1          3.5           NaN          0.3  Iris-setosa
17           5.7          3.8           NaN          0.3  Iris-setosa
18           5.1          3.8           NaN          0.3  Iris-setosa
19           5.4          3.4           NaN          0.2  Iris-setosa
20           5.1          3.7           NaN          0.4  Iris-setosa
21           4.6          3.6           NaN          0.2  Iris-setosa
22           5.1          3.3           NaN          0.5  Iris-setosa
23           4.8          3.4           NaN          0.2  Iris-setosa
24           5.0          3.0           NaN          0.2  Iris-setosa
25           5.0          3.4           NaN          0.4  Iris-setosa
26           5.2          3.5           NaN          0.2  Iris-setosa
27           5.2          3.4           NaN          0.2  Iris-setosa
28           4.7          3.2           NaN          0.2  Iris-setosa
29           4.8          3.1           NaN          0.2  Iris-setosa
30           5.4          3.4           1.5          0.4  Iris-setosa
31           5.2          4.1           1.5          0.1  Iris-setosa

## Step 7. Good, now lets substitute the NaN values to 1.0

In [19]:
iris.fillna(1.0)

     sepal_length  sepal_width  petal_length  petal_width           class
0             4.9          3.0           1.4          0.2     Iris-setosa
1             4.7          3.2           1.3          0.2     Iris-setosa
2             4.6          3.1           1.5          0.2     Iris-setosa
3             5.0          3.6           1.4          0.2     Iris-setosa
4             5.4          3.9           1.7          0.4     Iris-setosa
5             4.6          3.4           1.4          0.3     Iris-setosa
6             5.0          3.4           1.5          0.2     Iris-setosa
7             4.4          2.9           1.4          0.2     Iris-setosa
8             4.9          3.1           1.5          0.1     Iris-setosa
9             5.4          3.7           1.5          0.2     Iris-setosa
10            4.8          3.4           1.0          0.2     Iris-setosa
11            4.8          3.0           1.0          0.1     Iris-setosa
12            4.3          3.0           1.0          0.1     Iris-setosa
13            5.8          4.0           1.0          0.2     Iris-setosa
14            5.7          4.4           1.0          0.4     Iris-setosa
15            5.4          3.9           1.0          0.4     Iris-setosa
16            5.1          3.5           1.0          0.3     Iris-setosa
17            5.7          3.8           1.0          0.3     Iris-setosa
18            5.1          3.8           1.0          0.3     Iris-setosa
19            5.4          3.4           1.0          0.2     Iris-setosa
20            5.1          3.7           1.0          0.4     Iris-setosa
21            4.6          3.6           1.0          0.2     Iris-setosa
22            5.1          3.3           1.0          0.5     Iris-setosa
23            4.8          3.4           1.0          0.2     Iris-setosa
24            5.0          3.0           1.0          0.2     Iris-setosa
25            5.0          3.4           1.0          0.4     Iris-setosa
26            5.2          3.5           1.0          0.2     Iris-setosa
27            5.2          3.4           1.0          0.2     Iris-setosa
28            4.7          3.2           1.0          0.2     Iris-setosa
29            4.8          3.1           1.0          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
119           6.9          3.2           5.7          2.3  Iris-virginica
120           5.6          2.8           4.9          2.0  Iris-virginica
121           7.7          2.8           6.7          2.0  Iris-virginica
122           6.3          2.7           4.9          1.8  Iris-virginica
123           6.7          3.3           5.7          2.1  Iris-virginica
124           7.2          3.2           6.0          1.8  Iris-virginica
125           6.2          2.8           4.8          1.8  Iris-virginica
126           6.1          3.0           4.9          1.8  Iris-virginica
127           6.4          2.8           5.6          2.1  Iris-virginica
128           7.2          3.0           5.8          1.6  Iris-virginica
129           7.4          2.8           6.1          1.9  Iris-virginica
130           7.9          3.8           6.4          2.0  Iris-virginica
131           6.4          2.8           5.6          2.2  Iris-virginica
132           6.3          2.8           5.1          1.5  Iris-virginica
133           6.1          2.6           5.6          1.4  Iris-virginica
134           7.7          3.0           6.1          2.3  Iris-virginica
135           6.3          3.4           5.6          2.4  Iris-virginica
136           6.4          3.1           5.5          1.8  Iris-virginica
137           6.0          3.0           4.8          1.8  Iris-virginica
138           6.9          3.1           5.4          2.1  Iris-virginica
139           6.7          3.1           5.6          2.4  Iris-virginica
140           6.9          3.1           5.1          2.3  Iris-virginica
141           5.8          2.7           5.1          1.9  Iris-virginica
142           6.8          3.2           5.9          2.3  Iris-virginica
143           6.7          3.3           5.7          2.5  Iris-virginica
144           6.7          3.0           5.2          2.3  Iris-virginica
145           6.3          2.5           5.0          1.9  Iris-virginica
146           6.5          3.0           5.2          2.0  Iris-virginica
147           6.2          3.4           5.4          2.3  Iris-virginica
148           5.9          3.0           5.1          1.8  Iris-virginica

[149 rows x 5 columns]

## Step 8. Now let's delete the column class

In [20]:
del iris['class']

iris.head()

   sepal_length  sepal_width  petal_length  petal_width
0           4.9          3.0           1.4          0.2
1           4.7          3.2           1.3          0.2
2           4.6          3.1           1.5          0.2
3           5.0          3.6           1.4          0.2
4           5.4          3.9           1.7          0.4

## Step 9. Set the first 3 rows as NaN

In [22]:
iris.loc[0:2,:] = np.NaN

iris.head()

   sepal_length  sepal_width  petal_length  petal_width
0           NaN          NaN           NaN          NaN
1           NaN          NaN           NaN          NaN
2           NaN          NaN           NaN          NaN
3           5.0          3.6           1.4          0.2
4           5.4          3.9           1.7          0.4

## Step 10. Delete the rows that have NaN

In [0]:
iris.dropna(inplace=True)

In [24]:
iris.head()

   sepal_length  sepal_width  petal_length  petal_width
3           5.0          3.6           1.4          0.2
4           5.4          3.9           1.7          0.4
5           4.6          3.4           1.4          0.3
6           5.0          3.4           1.5          0.2
7           4.4          2.9           1.4          0.2

## Step 11. Reset the index so it begins with 0 again

In [25]:
iris.reset_index(drop=True)

     sepal_length  sepal_width  petal_length  petal_width
0             5.0          3.6           1.4          0.2
1             5.4          3.9           1.7          0.4
2             4.6          3.4           1.4          0.3
3             5.0          3.4           1.5          0.2
4             4.4          2.9           1.4          0.2
5             4.9          3.1           1.5          0.1
6             5.4          3.7           1.5          0.2
7             5.4          3.4           1.5          0.4
8             5.2          4.1           1.5          0.1
9             5.5          4.2           1.4          0.2
10            4.9          3.1           1.5          0.1
11            5.0          3.2           1.2          0.2
12            5.5          3.5           1.3          0.2
13            4.9          3.1           1.5          0.1
14            4.4          3.0           1.3          0.2
15            5.1          3.4           1.5          0.2
16            5.0          3.5           1.3          0.3
17            4.5          2.3           1.3          0.3
18            4.4          3.2           1.3          0.2
19            5.0          3.5           1.6          0.6
20            5.1          3.8           1.9          0.4
21            4.8          3.0           1.4          0.3
22            5.1          3.8           1.6          0.2
23            4.6          3.2           1.4          0.2
24            5.3          3.7           1.5          0.2
25            5.0          3.3           1.4          0.2
26            7.0          3.2           4.7          1.4
27            6.4          3.2           4.5          1.5
28            6.9          3.1           4.9          1.5
29            5.5          2.3           4.0          1.3
..            ...          ...           ...          ...
96            6.9          3.2           5.7          2.3
97            5.6          2.8           4.9          2.0
98            7.7          2.8           6.7          2.0
99            6.3          2.7           4.9          1.8
100           6.7          3.3           5.7          2.1
101           7.2          3.2           6.0          1.8
102           6.2          2.8           4.8          1.8
103           6.1          3.0           4.9          1.8
104           6.4          2.8           5.6          2.1
105           7.2          3.0           5.8          1.6
106           7.4          2.8           6.1          1.9
107           7.9          3.8           6.4          2.0
108           6.4          2.8           5.6          2.2
109           6.3          2.8           5.1          1.5
110           6.1          2.6           5.6          1.4
111           7.7          3.0           6.1          2.3
112           6.3          3.4           5.6          2.4
113           6.4          3.1           5.5          1.8
114           6.0          3.0           4.8          1.8
115           6.9          3.1           5.4          2.1
116           6.7          3.1           5.6          2.4
117           6.9          3.1           5.1          2.3
118           5.8          2.7           5.1          1.9
119           6.8          3.2           5.9          2.3
120           6.7          3.3           5.7          2.5
121           6.7          3.0           5.2          2.3
122           6.3          2.5           5.0          1.9
123           6.5          3.0           5.2          2.0
124           6.2          3.4           5.4          2.3
125           5.9          3.0           5.1          1.8

[126 rows x 4 columns]